server:
  port: 8080
spring:
  application:
     name: AnueTest #服務名稱
  datasource:
    url: jdbc:mysql://192.168.1.168:3306/anueTest_schema?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.1.168
    port: 6379
    database: 0
    password: 123456
    timeout: 3000
    jedis:
      pool:
        max-active: 50
        min-idle: 5
        max-wait: 3000
        max-idle: 20

mybatis:
  type-aliases-package: com.mypet.pojo
  mapper-locations: classpath:*Mapper.xml #mapper.xml所在位置
  config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路徑

swagger:
  enable: true